get_groupe:
    path:    /groupe/get.{_format}
    defaults: { _controller: "RoadBundle:Groupe:getGroupe" }
    methods:  GET

groupe_new:
    path:     /groupe/new.{_format}
    defaults: { _controller: "RoadBundle:Groupe:newgroupe" }
    methods:  POST

groupe_delete:
    path:     /groupe/delete/{id}.{_format}
    defaults: { _controller: "RoadBundle:Groupe:deleteGroupe" }
    methods:  DELETE

get_budget:
    path:    /budget/get/{id}.{_format}
    defaults: { _controller: "RoadBundle:Budget:getBudget" }
    methods:  GET

budget_new:
    path:     /budget/new/{id}.{_format}
    defaults: { _controller: "RoadBundle:Budget:newbudget" }
    methods:  POST

budget_update:
    path:     /budget/update/{id}.{_format}
    defaults: { _controller: "RoadBundle:Budget:updatebudget" }
    methods:  PUT

budget_delete:
    path:     /budget/delete/{id}.{_format}
    defaults: { _controller: "RoadBundle:Budget:deletebudget" }
    methods:  DELETE
