<?php

namespace RoadBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use RoadBundle\Form\BudgetType;
use RoadBundle\Entity\Budget;
use RoadBundle\Form\MembreType;
use RoadBundle\Entity\Membre;
use RoadBundle\Entity\Groupe;

use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\View\View;

class UserbudgetController extends Controller
{
    public function userBudgetAction(Request $request, $idmembre)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository("RoadBundle:Membre")->findOneByIdmembre($idmembre);
        $budUsers = $em->getRepository("RoadBundle:Budget")->findbyIdmembre($idmembre);
        $budget = $em->getRepository("RoadBundle:Budget")->findOneByIdgroupe($user->getIdgroupe());

        $count = 0;
        foreach ($budUsers as $budUser){
        $totalUser = $budUser->getTotal();
        $count += $totalUser;
    }
        
        $totalbudget = $budget->getTotal();
    
        $effvalue = $totalbudget - $count;
        
        return array('budget' => $budget,
            'effvalue' => $effvalue,
            'budUsers' => $budUsers,
        );
    
    }
}