road:
    resource: "@RoadBundle/Resources/config/routing.yml"
    prefix:   /

apirest:
    resource: "@ApirestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

test:
    path:     /new
    defaults: { _controller: "RoadBundle:Groupe:test" }
